CREATE TABLE IF NOT EXISTS words
(
    word VARCHAR NOT NULL PRIMARY KEY,
    a    INT,
    b    INT,
    v    INT,
    g    INT,
    d    INT,
    e    INT,
    yo   INT,
    je   INT,
    z    INT,
    i    INT,
    ji   INT,
    k    INT,
    l    INT,
    m    INT,
    n    INT,
    o    INT,
    p    INT,
    r    INT,
    s    INT,
    t    INT,
    u    INT,
    f    INT,
    h    INT,
    ce   INT,
    ch   INT,
    sh   INT,
    she  INT,
    tvd  INT,
    yi   INT,
    mgk  INT,
    ee   INT,
    yu   INT,
    ya   INT
);